### ISSUE TITLE
Implement serialisation

### ISSUE THREAD

**Issue by reedy** [maxwilms/bloom-filter#1]
It'd be useful if the results could be serialised so they can be saved to a file

**Comment by maxwilms** [comment]
Hey!

The built-in `serialize()` function of PHP should work like a charm. Or do I miss something?

```
$bloomFilter = BloomFilterGenerator::generate(1000, 0.01); 

$bloomFilter->add('foo');
$bloomFilter->add('bar');

// serialize $bloomFilter and store the result everywhere you want.
$res = serialize($bloomFilter);

// load $res and use it
$unres = unserialize($res);

$unres->contains('foo');
$unres->contains('baz');
```

**Comment by reedy** [comment]
I... Can't even remember if I tried that... Will check and get back to you :)

**Comment by reedy** [comment]
Yup, it works fine. Sorry for the disturbance ;)

Reproducible build too, which is always nice.

Thanks!
