### ISSUE TITLE
Define php version compatibility in composer.json

### ISSUE THREAD

**Issue by reedy** [maxwilms/bloom-filter#2]
There's no PHP version compatibility defined in composer.json...

The closest I can see is >= 5.4 in travis.yaml - would that be right?

**Comment by maxwilms** [comment]
Hello!

Yes, version v0.9.* is compatible with PHP >= 5.4 according to travis (https://travis-ci.org/maxwilms/bloom-filter)

I'm unsure about your `composer.json` request. As far as I can see there is a PHP version defined:
https://github.com/maxwilms/bloom-filter/blob/v0.9.3/composer.json#L15

Is there anything wrong with this definition?

But in any case I just released a new version v0.9.4 which requires at least "5.4" and not "5.4.36"
https://github.com/maxwilms/bloom-filter/blob/v0.9.4/composer.json#L16

**Comment by reedy** [comment]
I'm sorry for repeatedly wasting your time. I'm going to blame a lack of sleep, and being up late.

It's obviously there, and I don't know how I managed to be completely blind enough not to see it :/
